<?php

/**
 * @author Generated by Data Object Generator
 * @version 1.0
 */

require_once('Database/Abstraction/AttributeMappedDataObject.class.php');

class customerDataObject extends AttributeMappedDataObject
{
        /*
	 * Class Constants
	 */
	
        
	function TABLE () { return 'customer'; }
	function PRIMARY_KEY () { return 'id'; }
	
        function FIELD_LIST () { return array(
                 'id',
                 'firstname',
                 'surname',
                 'title',
                 'company_name',
                 'building_name',
                 'building_number',
                 'street',
                 'area',
                 'city',
                 'county',
                 'country',
                 'postcode',
                 'email',
				 'giftaid',
                 'username',
                 'password'
                ); }
                
        function ATTRIBUTE2FIELD_MAP () { return array(
                'id' => 'id',
                'firstname' => 'firstname',
                'surname' => 'surname',
                'title' => 'title',
                'company_name' => 'company_name',
                'building_name' => 'building_name',
                'building_number' => 'building_number',
                'street' => 'street',
                'area' => 'area',
                'city' => 'city',
                'county' => 'county',
                'country' => 'country',
                'postcode' => 'postcode',
                'email' => 'email',
				'giftaid' => 'giftaid',
                'username' => 'username',
                'password' => 'password'
                ); }
        
        function ATTRIBUTE2FIELD_CONV () { return array(); }
        function FIELD2ATTRIBUTE_CONV () { return array(); }
        
        
        /*
	 * Class Variables
	 */
        
        
	/*
	 * Instance Variables
	 */
        
	var $id = '';
	var $firstname = NULL;
	var $surname = NULL;
	var $title = NULL;
	var $company_name = NULL;
	var $building_name = NULL;
	var $building_number = NULL;
	var $street = NULL;
	var $area = NULL;
	var $city = NULL;
	var $county = NULL;
	var $country = NULL;
	var $postcode = NULL;
	var $email = NULL;
	var $giftaid = NULL;
	var $username = NULL;
	var $password = NULL;

        /*
	 * Class Methods
	 */
        
        
        /*
	 * Constructors
	 */
	 
	 
        function customerDataObject ()
        {
                $numArgs = func_num_args();
                $args = func_get_args();
                call_user_func_array(
                        array(&$this, '_customerDataObject'.$numArgs),
                        $args);
        }
        
        
        function _customerDataObject0 ()
        {
                $this->_initialize();
        }
        
        
        /*
	 * Accessor & Mutator Methods
	 */
	 
	 
	function setid( $tempid )
	{	
		$this->id = $tempid;
	}
	
	function getid()
	{	
		return $this->id;
	}
	
	function setGiftaid( $tempgiftaid )
	{	
		$this->giftaid = $tempgiftaid;
	}
	
	function getGiftaid()
	{	
		return $this->giftaid;
	}
	
	function setfirstname( $tempfirstname )
	{	
		$this->firstname = $tempfirstname;
	}
	
	function getfirstname()
	{	
		return $this->firstname;
	}
	
	function setsurname( $tempsurname )
	{	
		$this->surname = $tempsurname;
	}
	
	function getsurname()
	{	
		return $this->surname;
	}
	
	function settitle( $temptitle )
	{	
		$this->title = $temptitle;
	}
	
	function gettitle()
	{	
		return $this->title;
	}
	
	function setcompany_name( $tempcompany_name )
	{	
		$this->company_name = $tempcompany_name;
	}
	
	function getcompany_name()
	{	
		return $this->company_name;
	}
	
	function setbuilding_name( $tempbuilding_name )
	{	
		$this->building_name = $tempbuilding_name;
	}
	
	function getbuilding_name()
	{	
		return $this->building_name;
	}
	
	function setbuilding_number( $tempbuilding_number )
	{	
		$this->building_number = $tempbuilding_number;
	}
	
	function getbuilding_number()
	{	
		return $this->building_number;
	}
	
	function setstreet( $tempstreet )
	{	
		$this->street = $tempstreet;
	}
	
	function getstreet()
	{	
		return $this->street;
	}
	
	function setarea( $temparea )
	{	
		$this->area = $temparea;
	}
	
	function getarea()
	{	
		return $this->area;
	}
	
	function setcity( $tempcity )
	{	
		$this->city = $tempcity;
	}
	
	function getcity()
	{	
		return $this->city;
	}
	
	function setcounty( $tempcounty )
	{	
		$this->county = $tempcounty;
	}
	
	function getcounty()
	{	
		return $this->county;
	}
	
	function setcountry( $tempcountry )
	{	
		$this->country = $tempcountry;
	}
	
	function getcountry()
	{	
		return $this->country;
	}
	
	function setpostcode( $temppostcode )
	{	
		$this->postcode = $temppostcode;
	}
	
	function getpostcode()
	{	
		return $this->postcode;
	}
	
	function setemail( $tempemail )
	{	
		$this->email = $tempemail;
	}
	
	function getemail()
	{	
		return $this->email;
	}
	
	function setusername( $tempusername )
	{	
		$this->username = $tempusername;
	}
	
	function getusername()
	{	
		return $this->username;
	}
	
	function setpassword( $temppassword )
	{	
		$this->password = $temppassword;
	}
	
	function getpassword()
	{	
		return $this->password;
	}
	

        /*
	 * Command Methods
	 */
        
        
        function &_instantiateDataObject ()
        {
                $obj =& new customerDataObject();
                
                return $obj;
        }
        
        
        function _postinsert ( &$connection )
        {
                $this->setid($connection->getLastInsertId());
        }
        
}

?>
