<?php

/**
 * @author Generated by Data Object Generator
 * @version 1.0
 */

require_once('Database/Abstraction/AttributeMappedDataObject.class.php');

class unapprovedimagesDataObject extends AttributeMappedDataObject
{
        /*
	 * Class Constants
	 */
	
        
	function TABLE () { return 'unapprovedimages'; }
	function PRIMARY_KEY () { return 'id'; }
	
        function FIELD_LIST () { return array(
                 'id',
                 'name',
                 'description',
                 'approved',
                 'alt',
                 'filename',
                 'thumbnail',
                ); }
                
        function ATTRIBUTE2FIELD_MAP () { return array(
                'id' => 'id',
                'name' => 'name',
                'description' => 'description',
                'approved' => 'approved',
                'alt' => 'alt',
                'filename' => 'filename',
                'thumbnail' => 'thumbnail',
                ); }
        
        function ATTRIBUTE2FIELD_CONV () { return array(); }
        function FIELD2ATTRIBUTE_CONV () { return array(); }
        
        
        /*
	 * Class Variables
	 */
        
        
	/*
	 * Instance Variables
	 */
        
	var $id = NULL;
	var $name = NULL;
	var $description = NULL;
	var $approved = NULL;
	var $alt = NULL;
	var $filename = NULL;
	var $thumbnail = NULL;

        /*
	 * Class Methods
	 */
        
        
        /*
	 * Constructors
	 */
	 
	 
        function unapprovedimagesDataObject ()
        {
                $numArgs = func_num_args();
                $args = func_get_args();
                call_user_func_array(
                        array(&$this, '_unapprovedimagesDataObject'.$numArgs),
                        $args);
        }
        
        
        function _unapprovedimagesDataObject0 ()
        {
                $this->_initialize();
        }
        
        
        /*
	 * Accessor & Mutator Methods
	 */
	 
	 
	function setid( $tempid )
	{	
		$this->id = $tempid;
	}
	
	function getid()
	{	
		return $this->id;
	}
	
	function setname( $tempname )
	{	
		$this->name = $tempname;
	}
	
	function getname()
	{	
		return $this->name;
	}
	
	function setdescription( $tempdescription )
	{	
		$this->description = $tempdescription;
	}
	
	function getdescription()
	{	
		return $this->description;
	}
	
	function setapproved( $tempapproved )
	{	
		$this->approved = $tempapproved;
	}
	
	function getapproved()
	{	
		return $this->approved;
	}
	
	function setalt( $tempalt )
	{	
		$this->alt = $tempalt;
	}
	
	function getalt()
	{	
		return $this->alt;
	}
	
	function setfilename( $tempfilename )
	{	
		$this->filename = $tempfilename;
	}
	
	function getfilename()
	{	
		return $this->filename;
	}
	
	function setthumbnail( $tempthumbnail )
	{	
		$this->thumbnail = $tempthumbnail;
	}
	
	function getthumbnail()
	{	
		return $this->thumbnail;
	}
	

        /*
	 * Command Methods
	 */
        
        
        function &_instantiateDataObject ()
        {
                $obj =& new unapprovedimagesDataObject();
                
                return $obj;
        }
        
        
        function _postinsert ( &$connection )
        {
                $this->setid($connection->getLastInsertId());
        }
        
}

?>
